### ISSUE TITLE
Chapter 4 - Page 86 Typo

### ISSUE THREAD

**Issue by drdexter33** [PacktPublishing/Learning-Angular-Fourth-Edition#2]
In chapter 4 on page 86 I was struggling to get an example from the book to work and discovered it was due to a typographic error in this example for step 5:

![image](https://github.com/PacktPublishing/Learning-Angular-Fourth-Edition/assets/15314276/bc7f8da6-9470-4696-afd0-2efb3fff25ce)

The issue is that if you use single quotes as shown in the example, the alert just outputs the string as written, IE:

![image](https://github.com/PacktPublishing/Learning-Angular-Fourth-Edition/assets/15314276/98f5132e-3245-400c-9937-2da706124995)

In order to get the code to work, the single quotes need to be changed to backtick/grave accent characters:

![image](https://github.com/PacktPublishing/Learning-Angular-Fourth-Edition/assets/15314276/7de8d039-406f-4165-bb60-ce71c32e5297)

Which produces the expected result:

![image](https://github.com/PacktPublishing/Learning-Angular-Fourth-Edition/assets/15314276/d4594a57-22cf-4326-ae38-f91057894bf1)

**Comment by bampakoa** [comment]
Thank you very much for reporting that @drdexter33 🙏  We are already aware of this issue as another user has reported it on the Discord server of the book 🙂 Please let us know if you find anything related!
